"""Initial migration

Revision ID: 2e347743dc1e
Revises: 
Create Date: 2026-02-09 21:25:07.581673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e347743dc1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awareness_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('crime', 'law', 'guideline', name='awarenesscategory'), nullable=False),
    sa.Column('source', sa.Enum('ngo', 'govt', 'admin', name='awarenesssource'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awareness_posts_category'), 'awareness_posts', ['category'], unique=False)
    op.create_index(op.f('ix_awareness_posts_id'), 'awareness_posts', ['id'], unique=False)
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('NGO', 'LAWYER', 'PSYCHOLOGIST', name='mentorrole'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.create_index(op.f('ix_mentors_role'), 'mentors', ['role'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', 'ngo', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_phone_number'), 'contacts', ['phone_number'], unique=True)
    op.create_table('live_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_locations_id'), 'live_locations', ['id'], unique=False)
    op.create_table('mentorship_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Enum('LEGAL_ADVICE', 'EMOTIONAL_SUPPORT', 'SAFETY_PLANNING', 'REPORTING_GUIDANCE', name='mentorshiptopic'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CLOSED', name='mentorshipstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_sessions_id'), 'mentorship_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_mentorship_sessions_mentor_id'), 'mentorship_sessions', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentorship_sessions_user_id'), 'mentorship_sessions', ['user_id'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('awareness_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['awareness_id'], ['awareness_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'awareness_id', name='unique_user_awareness_reaction')
    )
    op.create_index(op.f('ix_reactions_awareness_id'), 'reactions', ['awareness_id'], unique=False)
    op.create_index(op.f('ix_reactions_id'), 'reactions', ['id'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    op.create_table('sos_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_events_id'), 'sos_events', ['id'], unique=False)
    op.create_table('mentorship_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MENTOR', name='messagerole'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('is_filtered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['mentorship_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_messages_id'), 'mentorship_messages', ['id'], unique=False)
    op.create_index(op.f('ix_mentorship_messages_session_id'), 'mentorship_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentorship_messages_session_id'), table_name='mentorship_messages')
    op.drop_index(op.f('ix_mentorship_messages_id'), table_name='mentorship_messages')
    op.drop_table('mentorship_messages')
    op.drop_index(op.f('ix_sos_events_id'), table_name='sos_events')
    op.drop_table('sos_events')
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_awareness_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_mentorship_sessions_user_id'), table_name='mentorship_sessions')
    op.drop_index(op.f('ix_mentorship_sessions_mentor_id'), table_name='mentorship_sessions')
    op.drop_index(op.f('ix_mentorship_sessions_id'), table_name='mentorship_sessions')
    op.drop_table('mentorship_sessions')
    op.drop_index(op.f('ix_live_locations_id'), table_name='live_locations')
    op.drop_table('live_locations')
    op.drop_index(op.f('ix_contacts_phone_number'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mentors_role'), table_name='mentors')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_awareness_posts_id'), table_name='awareness_posts')
    op.drop_index(op.f('ix_awareness_posts_category'), table_name='awareness_posts')
    op.drop_table('awareness_posts')
    # ### end Alembic commands ###
